"use client";

import React, { useState } from "react";
import { IconTerraform, IconCheck, IconCopy, IconCode } from "./Icons";

export function TerraformViewer() {
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<"main" | "variables" | "outputs">("main");

  const terraformMainCode = `# AWS Amplify Next.js App Provisioning via Terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# 1. Amplify Application Resource
resource "aws_amplify_app" "nextjs_sandbox" {
  name       = "amplify-sandbox-fe"
  repository = "https://github.com/omotomiwa26/amplify-sandbox-fe"

  # Build Spec for Next.js App Router
  build_spec = <<-EOT
    version: 1
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - .next/cache/**/*
          - node_modules/**/*
  EOT

  # Enable Next.js SSR Web Compute
  platform = "WEB_COMPUTE"

  environment_variables = {
    AMPLIFY_MONOREPO_APP_ROOT = "/"
    NODE_ENV                  = "production"
  }
}

# 2. Amplify Main Branch Setup
resource "aws_amplify_branch" "main" {
  app_id      = aws_amplify_app.nextjs_sandbox.id
  branch_name = "main"

  framework = "Next.js - SSR"
  stage     = "PRODUCTION"
}`;

  const terraformVarsCode = `variable "aws_region" {
  description = "AWS region for Amplify deployment"
  type        = string
  default     = "us-east-1"
}

variable "repository_name" {
  description = "GitHub repository link"
  type        = string
  default     = "https://github.com/omotomiwa26/amplify-sandbox-fe"
}

variable "branch_name" {
  description = "Target git branch to build"
  type        = string
  default     = "main"
}`;

  const terraformOutputsCode = `output "amplify_app_id" {
  description = "The unique ID of the created AWS Amplify App"
  value       = aws_amplify_app.nextjs_sandbox.id
}

output "amplify_default_domain" {
  description = "The default URL generated by AWS Amplify"
  value       = aws_amplify_app.nextjs_sandbox.default_domain
}

output "amplify_branch_status" {
  description = "Status of the production branch deployment"
  value       = aws_amplify_branch.main.stage
}`;

  const activeCode =
    activeTab === "main"
      ? terraformMainCode
      : activeTab === "variables"
      ? terraformVarsCode
      : terraformOutputsCode;

  const copyCode = () => {
    navigator.clipboard.writeText(activeCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section className="py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
          <div>
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <IconTerraform className="w-5 h-5 text-purple-400" />
              Terraform HCL Infrastructure Inspector
            </h2>
            <p className="text-xs text-slate-400 mt-1">
              Declarative Terraform code managing `aws_amplify_app` and `aws_amplify_branch`.
            </p>
          </div>

          <div className="flex items-center space-x-2 bg-slate-900 p-1 rounded-xl border border-slate-800">
            {(["main", "variables", "outputs"] as const).map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-3 py-1.5 rounded-lg text-xs font-mono transition-all capitalize ${
                  activeTab === tab
                    ? "bg-purple-600 text-white font-bold shadow-md"
                    : "text-slate-400 hover:text-white"
                }`}
              >
                {tab === "main" ? "main.tf" : tab === "variables" ? "variables.tf" : "outputs.tf"}
              </button>
            ))}
          </div>
        </div>

        {/* Code Display Window */}
        <div className="glass-panel rounded-2xl overflow-hidden border border-slate-800">
          
          {/* Header Bar */}
          <div className="bg-slate-950 px-4 py-3 border-b border-slate-800 flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <span className="w-3 h-3 rounded-full bg-red-500/80"></span>
              <span className="w-3 h-3 rounded-full bg-amber-500/80"></span>
              <span className="w-3 h-3 rounded-full bg-emerald-500/80"></span>
              <span className="ml-2 text-xs font-mono text-slate-400">
                terraform/{activeTab === "main" ? "main.tf" : activeTab === "variables" ? "variables.tf" : "outputs.tf"}
              </span>
            </div>

            <button
              onClick={copyCode}
              className="inline-flex items-center space-x-1.5 px-3 py-1 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-700 text-xs text-slate-300 transition-colors"
            >
              {copied ? <IconCheck className="w-3.5 h-3.5 text-emerald-400" /> : <IconCopy className="w-3.5 h-3.5" />}
              <span>{copied ? "Copied HCL" : "Copy Code"}</span>
            </button>
          </div>

          {/* Code Container */}
          <div className="p-6 bg-slate-950/90 font-mono text-xs overflow-x-auto text-purple-300 leading-relaxed">
            <pre>{activeCode}</pre>
          </div>

        </div>

      </div>
    </section>
  );
}
